version: "3"

services:
  db:
    image: postgres:12.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastannotation
    ports:
      - "19000:5432"
    networks:
      - datanodes
  app:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - datanodes

networks:
  datanodes:
    driver: bridge
